CREATE TABLE IF NOT EXISTS enneagram(
    id serial PRIMARY KEY,
    archetype VARCHAR(128) UNIQUE NOT NULL,
    enneagram_description VARCHAR(512) NOT NULL,
    center VARCHAR(128) NOT NULL,
    dominant_emotion VARCHAR(128) NOT NULL,
    keywords VARCHAR(128) NOT NULL,
    fear VARCHAR(128),
    desire VARCHAR(128) NOT NULL,
    wings_1 INT NOT NULL,
    wings_2 INT NOT NULL,
    -- lod_level VARCHAR(128) NOT NULL,
    -- current_lod VARCHAR(128) NOT NULL,
    level_of_development_1 VARCHAR(512) NOT NULL,
    level_of_development_2 VARCHAR(512) NOT NULL,
    level_of_development_3 VARCHAR(512) NOT NULL,
    level_of_development_4 VARCHAR(512) NOT NULL,
    level_of_development_5 VARCHAR(512) NOT NULL,
    level_of_development_6 VARCHAR(512) NOT NULL,
    level_of_development_7 VARCHAR(512) NOT NULL,
    level_of_development_8 VARCHAR(512) NOT NULL,
    level_of_development_9 VARCHAR(512) NOT NULL,
    key_motivations VARCHAR(512) NOT NULL,
    overview VARCHAR(512) NOT NULL,
    addictions VARCHAR(512) NOT NULL,
    growth_recommendations_1 VARCHAR(1024) NOT NULL,
    growth_recommendations_2 VARCHAR(1024) NOT NULL,
    growth_recommendations_3 VARCHAR(1024) NOT NULL,
    growth_recommendations_4 VARCHAR(1024) NOT NULL,
    growth_recommendations_5 VARCHAR(1024) NOT NULL
);