CREATE TABLE IF NOT EXISTS races_5e(
    id serial PRIMARY KEY,
    race VARCHAR(128) NOT NULL,
    subrace VARCHAR(256) NOT NULL,
    adult_age_min INT NOT NULL,
    adult_age_max INT NOT NULL,
    covering VARCHAR(128) NOT NULL,
    convering_alt VARCHAR(128),
    incidence VARCHAR(128) NOT NULL,
    race_size VARCHAR(128) NOT NULL,
    speed INT NOT NULL,
    race_language VARCHAR(128) NOT NULL,
    strength INT NOT NULL,
    dexterity INT NOT NULL,
    constitution INT NOT NULL,
    intelligence INT NOT NULL,
    wisdom INT NOT NULL,
    charisma INT NOT NULL,
    extra VARCHAR(256)
);