version: '3.7'
services:
  npcg-app:
    build:
      context: .
    container_name: npcg-app
    environment:
      PORT: ${SERVER_PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - '${SERVER_NETWORK}'

  postgres:
    image: postgres:10.5
    restart: always
    container_name: npcg-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: [ CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - '${SERVER_NETWORK}'

volumes:
  postgres-data:


networks: ${SERVER_NETWORK}
