# Database Configurations
database:
  dbpath: db/npcgendata.db
  csvpath: data/raw/csv
  jsonpath: data/raw/json
  migrationpath: file://internal/sql/migrations
  files:
    - filename: Fantasy_Names.csv
      required: true
      header: false
      tablename: names_fantasy
    - filename: Genders.csv
      required: true
      header: true
      tablename: genders
    - filename: NPC_Job_List_Fantasy.csv
      required: true
      header: true
      tablename: jobs_fantasy
    - filename: Races_5e.csv
      required: true
      header: true
      tablename: races_5e
    - filename: Sexual_Orientations.csv
      required: true
      header: true
      tablename: sex_orientations_npc
    - filename: NPC_Cognitive_Data.csv
      required: true
      header: true
      tablename: cognitive_data_npc
    - filename: enneagramData.json
      required: true
      header: false
      tablename: enneagram
    - filename: Fantasy_Names_NGrams.csv
      required: false
      header: false
      tablename: ngrams_fantasy